[project]
name = "videxplainagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromadb>=0.3.23",
    "pydantic<2.0",
    "sentence-transformers>=5.1.2",
]
